"""
This file defines the baseline data.
These values gemerated by running dmon with the "--average" option.
"""
lookup = {
    "DOOM": {
        "easy": {
            "monsters": 38.3,
            "hitscanners": 13.2,
            "health points": 359.1,
            "armor points": 348.1,
            "bullets": 348.8,
            "shells": 154.1,
            "rockets": 27.5,
            "plasma cells": 233.3,
            "monster hit points": 4366.9,
            "monster attack points": 783.4,
            "hitscan %": 34.5,
            "health/AP": 0.5,
            "armor/AP": 0.4,
            "bullet/HP": 1.6,
            "shell/HP": 2.6,
            "rocket/HP": 0.6,
            "plasma/HP": 1.3
        },
        "medium": {
            "monsters": 65.6,
            "hitscanners": 22.0,
            "health points": 354.7,
            "armor points": 339.9,
            "bullets": 358.6,
            "shells": 171.2,
            "rockets": 27.6,
            "plasma cells": 219.4,
            "monster hit points": 7533.3,
            "monster attack points": 1316.0,
            "hitscan %": 33.5,
            "health/AP": 0.3,
            "armor/AP": 0.3,
            "bullet/HP": 0.9,
            "shell/HP": 1.7,
            "rocket/HP": 0.4,
            "plasma/HP": 0.7
        },
        "hard": {
            "monsters": 90.1,
            "hitscanners": 28.9,
            "health points": 340.1,
            "armor points": 329.1,
            "bullets": 362.2,
            "shells": 195.0,
            "rockets": 29.2,
            "plasma cells": 225.0,
            "monster hit points": 11033.3,
            "monster attack points": 1888.0,
            "hitscan %": 32.1,
            "health/AP": 0.2,
            "armor/AP": 0.2,
            "bullet/HP": 0.7,
            "shell/HP": 1.3,
            "rocket/HP": 0.3,
            "plasma/HP": 0.5
        }
    },
    "DOOM2": {
        "easy": {
            "monsters": 42.6,
            "hitscanners": 16.4,
            "health points": 343.4,
            "armor points": 240.8,
            "bullets": 339.1,
            "shells": 151.9,
            "rockets": 26.8,
            "plasma cells": 360.6,
            "monster hit points": 5765.0,
            "monster attack points": 995.7,
            "hitscan %": 38.5,
            "health/AP": 0.3,
            "armor/AP": 0.2,
            "bullet/HP": 1.2,
            "shell/HP": 2.0,
            "rocket/HP": 0.5,
            "plasma/HP": 1.6
        },
        "medium": {
            "monsters": 82.9,
            "hitscanners": 28.9,
            "health points": 355.6,
            "armor points": 240.9,
            "bullets": 353.9,
            "shells": 178.5,
            "rockets": 27.5,
            "plasma cells": 372.5,
            "monster hit points": 11988.4,
            "monster attack points": 2013.5,
            "hitscan %": 34.9,
            "health/AP": 0.2,
            "armor/AP": 0.1,
            "bullet/HP": 0.6,
            "shell/HP": 1.1,
            "rocket/HP": 0.2,
            "plasma/HP": 0.8
        },
        "hard": {
            "monsters": 117.0,
            "hitscanners": 37.8,
            "health points": 354.1,
            "armor points": 237.7,
            "bullets": 358.0,
            "shells": 190.9,
            "rockets": 27.5,
            "plasma cells": 371.9,
            "monster hit points": 16856.2,
            "monster attack points": 2765.0,
            "hitscan %": 32.3,
            "health/AP": 0.1,
            "armor/AP": 0.1,
            "bullet/HP": 0.4,
            "shell/HP": 0.8,
            "rocket/HP": 0.2,
            "plasma/HP": 0.6
        }
    },
    "SIGIL": {
        "easy": {
            "monsters": 39.2,
            "hitscanners": 12.2,
            "health points": 235.8,
            "armor points": 470.3,
            "bullets": 363.3,
            "shells": 183.1,
            "rockets": 22.0,
            "plasma cells": 368.9,
            "monster hit points": 5426.7,
            "monster attack points": 800.9,
            "hitscan %": 31.2,
            "health/AP": 0.3,
            "armor/AP": 0.6,
            "bullet/HP": 1.3,
            "shell/HP": 2.5,
            "rocket/HP": 0.4,
            "plasma/HP": 1.7
        },
        "medium": {
            "monsters": 68.2,
            "hitscanners": 22.2,
            "health points": 234.7,
            "armor points": 470.3,
            "bullets": 349.4,
            "shells": 221.8,
            "rockets": 21.3,
            "plasma cells": 342.2,
            "monster hit points": 10048.9,
            "monster attack points": 1606.8,
            "hitscan %": 32.6,
            "health/AP": 0.1,
            "armor/AP": 0.3,
            "bullet/HP": 0.7,
            "shell/HP": 1.7,
            "rocket/HP": 0.2,
            "plasma/HP": 0.8
        },
        "hard": {
            "monsters": 84.8,
            "hitscanners": 27.1,
            "health points": 178.1,
            "armor points": 413.1,
            "bullets": 334.4,
            "shells": 233.3,
            "rockets": 20.9,
            "plasma cells": 335.6,
            "monster hit points": 14686.7,
            "monster attack points": 2309.8,
            "hitscan %": 32.0,
            "health/AP": 0.1,
            "armor/AP": 0.2,
            "bullet/HP": 0.5,
            "shell/HP": 1.2,
            "rocket/HP": 0.1,
            "plasma/HP": 0.6
        }
    },
    "AV": {
        "easy": {
            "monsters": 171.5,
            "hitscanners": 45.2,
            "health points": 590.8,
            "armor points": 424.1,
            "bullets": 392.0,
            "shells": 424.5,
            "rockets": 138.7,
            "plasma cells": 1451.2,
            "monster hit points": 37803.4,
            "monster attack points": 6128.1,
            "hitscan %": 26.4,
            "health/AP": 0.1,
            "armor/AP": 0.1,
            "bullet/HP": 0.2,
            "shell/HP": 0.8,
            "rocket/HP": 0.4,
            "plasma/HP": 1.0
        },
        "medium": {
            "monsters": 251.5,
            "hitscanners": 62.1,
            "health points": 626.9,
            "armor points": 427.1,
            "bullets": 435.0,
            "shells": 540.0,
            "rockets": 172.4,
            "plasma cells": 1953.8,
            "monster hit points": 63510.3,
            "monster attack points": 10160.1,
            "hitscan %": 24.7,
            "health/AP": 0.1,
            "armor/AP": 0.0,
            "bullet/HP": 0.1,
            "shell/HP": 0.6,
            "rocket/HP": 0.3,
            "plasma/HP": 0.8
        },
        "hard": {
            "monsters": 342.0,
            "hitscanners": 80.9,
            "health points": 627.0,
            "armor points": 455.3,
            "bullets": 455.8,
            "shells": 608.4,
            "rockets": 194.2,
            "plasma cells": 2334.4,
            "monster hit points": 89788.1,
            "monster attack points": 14899.5,
            "hitscan %": 23.7,
            "health/AP": 0.0,
            "armor/AP": 0.0,
            "bullet/HP": 0.1,
            "shell/HP": 0.5,
            "rocket/HP": 0.2,
            "plasma/HP": 0.7
        }
    },
    "DTWID": {
        "easy": {
            "monsters": 65.6,
            "hitscanners": 21.4,
            "health points": 449.6,
            "armor points": 473.7,
            "bullets": 754.8,
            "shells": 266.5,
            "rockets": 54.7,
            "plasma cells": 331.1,
            "monster hit points": 7027.8,
            "monster attack points": 1224.2,
            "hitscan %": 32.6,
            "health/AP": 0.4,
            "armor/AP": 0.4,
            "bullet/HP": 2.1,
            "shell/HP": 2.8,
            "rocket/HP": 0.8,
            "plasma/HP": 1.2
        },
        "medium": {
            "monsters": 90.8,
            "hitscanners": 28.5,
            "health points": 450.7,
            "armor points": 470.2,
            "bullets": 769.8,
            "shells": 287.9,
            "rockets": 55.0,
            "plasma cells": 331.9,
            "monster hit points": 9981.5,
            "monster attack points": 1736.8,
            "hitscan %": 31.4,
            "health/AP": 0.3,
            "armor/AP": 0.3,
            "bullet/HP": 1.5,
            "shell/HP": 2.2,
            "rocket/HP": 0.6,
            "plasma/HP": 0.8
        },
        "hard": {
            "monsters": 108.9,
            "hitscanners": 35.1,
            "health points": 447.3,
            "armor points": 470.2,
            "bullets": 775.2,
            "shells": 307.4,
            "rockets": 54.8,
            "plasma cells": 331.9,
            "monster hit points": 12110.4,
            "monster attack points": 2124.0,
            "hitscan %": 32.3,
            "health/AP": 0.2,
            "armor/AP": 0.2,
            "bullet/HP": 1.3,
            "shell/HP": 1.9,
            "rocket/HP": 0.5,
            "plasma/HP": 0.7
        }
    },
    "HR": {
        "easy": {
            "monsters": 112.2,
            "hitscanners": 18.3,
            "health points": 577.5,
            "armor points": 308.7,
            "bullets": 424.4,
            "shells": 617.5,
            "rockets": 217.4,
            "plasma cells": 1283.8,
            "monster hit points": 36840.0,
            "monster attack points": 5360.3,
            "hitscan %": 16.3,
            "health/AP": 0.1,
            "armor/AP": 0.1,
            "bullet/HP": 0.2,
            "shell/HP": 1.3,
            "rocket/HP": 0.6,
            "plasma/HP": 0.9
        },
        "medium": {
            "monsters": 181.8,
            "hitscanners": 26.1,
            "health points": 600.9,
            "armor points": 327.5,
            "bullets": 432.0,
            "shells": 640.1,
            "rockets": 222.4,
            "plasma cells": 1345.0,
            "monster hit points": 63098.4,
            "monster attack points": 9110.0,
            "hitscan %": 14.3,
            "health/AP": 0.1,
            "armor/AP": 0.0,
            "bullet/HP": 0.1,
            "shell/HP": 0.8,
            "rocket/HP": 0.3,
            "plasma/HP": 0.5
        },
        "hard": {
            "monsters": 224.2,
            "hitscanners": 29.1,
            "health points": 570.9,
            "armor points": 315.0,
            "bullets": 425.0,
            "shells": 638.0,
            "rockets": 216.9,
            "plasma cells": 1304.4,
            "monster hit points": 83955.0,
            "monster attack points": 12123.3,
            "hitscan %": 13.0,
            "health/AP": 0.1,
            "armor/AP": 0.0,
            "bullet/HP": 0.1,
            "shell/HP": 0.6,
            "rocket/HP": 0.3,
            "plasma/HP": 0.4
        }
    }
}
